### ISSUE TITLE
Unknown plugin "typecheck"

### ISSUE THREAD

**Issue by anorudes** [bdefore/redux-universal-renderer#27] opened 2016-01-01 07:46 UTC
Hello, i see this error when try start universal-redux-server. Why is it showing?

```
throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
ReferenceError: Unknown plugin "typecheck" specified in "base" at 1
```

**Comment by bdefore** [comment] 2016-01-01 21:36
@anorudes can you tell me more about your setup? node, npm version. windows or os x? have you tried removing node_modules and reinstalling? i'm unable to reproduce this issue.

**Comment by arkist** [comment] 2016-01-04 02:16
@bdefore btw, where to use the typecheck plugin? is it really needed?

**Comment by bdefore** [comment] 2016-01-04 07:24
@arkist i'd really like to know more about this. if it's causing issues it might be best to pull this out of universal-redux and let people add it to their own project level babel configuration

**Comment by arkist** [comment] 2016-01-05 01:03
@bdefore [babel-plugin-typecheck](https://github.com/codemix/babel-plugin-typecheck) seems came from [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) but I can't find any of flow-typed code. or I missed something ¯_(ツ)_/¯
anyway, I can not see `ReferenceError` message in my mac/ubuntu machine.

**Comment by bdefore** [comment] 2016-01-05 03:42
@arkist you're right that typecheck is added in to the ancestor project without being used, as far as i can see. are you having issues with typecheck and universal-redux even when you're not using it? if so, i think it's worth pulling that out, but i cannot reproduce.

you can override the babel configuration (removing typecheck from starting) with your own with this setting: https://github.com/bdefore/universal-redux/blob/master/config/universal-redux.config.js#L88

**Comment by anorudes** [comment] 2016-01-05 04:48
@bdefore 
I was just trying to apply redux-universal in https://github.com/anorudes/redux-easy-boilerplate

**Comment by bdefore** [comment] 2016-01-12 17:06
@anorudes did you ever get around this issue with typecheck? could you try it out on 3.x? i'd be happy to help make a branch for your boilerplate running UR, and also given that yours does not have #7 i'd be curious to see if it could help me identify what's wrong there.

**Comment by bdefore** [comment] 2016-02-04 04:22
Closing, but if someone can reproduce with the latest builds please let me know.

**Closed as completed by bdefore** 2016-02-04 04:22 UTC
