### ISSUE TITLE
2.x RoutingContext Issues

### ISSUE THREAD

**Issue by mikeastock** [bdefore/redux-universal-renderer#33] opened 2016-01-05 06:13 UTC
I migrated an existing project following this PR:
https://github.com/erikras/react-redux-universal-hot-example/compare/master...bdefore:babel6.

When I start up my server I see the following warnings. Any ideas?

```
[1] Warning: Failed propType: Required prop `history` was not specified in `RoutingContext`.
[1] Warning: Failed propType: Required prop `location` was not specified in `RoutingContext`.
[1] Warning: Failed propType: Required prop `routes` was not specified in `RoutingContext`.
[1] Warning: Failed propType: Required prop `params` was not specified in `RoutingContext`.
[1] Warning: Failed propType: Required prop `components` was not specified in `RoutingContext`.
[1] Warning: Failed Context Types: Required child context `history` was not specified in `RoutingContext`.
[1] Warning: Failed Context Types: Required child context `location` was not specified in `RoutingContext`.
```

**Comment by bdefore** [comment] 2016-01-05 07:49
@mikeastock These are visually pretty annoying but are benign, and started happening with the change to redux-simple-router from redux-router. They are related to having removed renderProps from serverside rendering as a workaround to #16 and go away on 3.x with the new react-router API.

**Comment by shilpan** [comment] 2016-01-05 13:27
This is still reproducible in `3.0.0-beta5`. Is there a specific build this will be addressed in?

**Comment by shilpan** [comment] 2016-01-05 13:37
Sorry, the error I keep getting is 

```
[react-router] `props.history` and `context.history` are deprecated. Please use `context.router`
```

I am using `3.0.0-beta5`

**Comment by bdefore** [comment] 2016-01-05 16:32
@shilpan the error you see on 3.0.0 betas is an issue i hope to resolve once the official 2.0 redux-simple-router drops

**Comment by mikeastock** [comment] 2016-01-06 03:51
```

**Comment by mikeastock** [comment] 2016-01-06 03:52
I'm getting the following console error messages. Could they be caused by this?

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <div class="app___3sz
 (server) <noscript data-reactiwarning @ (program):45
(program):83 

Server-side React render was discarded. Make sure that your initial render does not contain any client-side code.
```

**Comment by bdefore** [comment] 2016-01-06 06:40
These will happen in the development environment, and may or may not indicate that your serverside render does not match the clientside render. The warnings in general are not very helpful in diagnosing whether or not this is a problem to be concerned about, and I'd like for them to be better.

**Comment by bdefore** [comment] 2016-01-14 20:03
@mikeastock @shilpan These errors should not be happening any more on 3.x. They will unfortunately still be there in 2.x until redux-simple-router and serverside render is reliable.

**Comment by bdefore** [comment] 2016-01-18 10:07
The checksum error due to `<noscript>` was fixed by https://github.com/bdefore/universal-redux/pull/46

**Closed as completed** 2016-07-11 03:05 UTC
